services:
  api:
    build: .
    container_name: express-api
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    volumes:
      - ./logs:/usr/src/app/logs   # optional: persist Winston logs
